#       .o8                                                                         
#      "888                                                                         
#  .oooo888   .ooooo.  oooo    ooo  .ooooo.   .ooooo.  ooo. .oo.  .oo.   oo.ooooo.  
# d88' `888  d88' `88b  `88.  .8'  d88' `"Y8 d88' `88b `888P"Y88bP"Y88b   888' `88b 
# 888   888  888ooo888   `88..8'   888       888   888  888   888   888   888   888 
# 888   888  888    .o    `888'    888   .o8 888   888  888   888   888   888   888 
# `Y8bod88P" `Y8bod8P'     `8'     `Y8bod8P' `Y8bod8P' o888o o888o o888o  888bod8P' 
#                                                                         888       
#                      ~/.config/starship.toml                           o888o

"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000
add_newline = true
format = """
$os$username$hostname:$directory$git_branch$git_status$git_commit$python$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$cmd_duration
$character
"""

# Replace the "❯"
[character]
success_symbol = "[♥](bright-purple)"
error_symbol = "[♥](red)"

[username]
style_user = "purple bold"
style_root = "white bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@$hostname](green bold)"
disabled = false
ssh_symbol = " "

# truncation length works backwards (i.e., cwd > parent > parent ...)
[directory]
truncation_length = 15
truncation_symbol = "…/"
truncate_to_repo = true
read_only = " 󰌾"

[git_branch]
truncation_length = 25
truncation_symbol = ''
symbol = " "

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'

[git_commit]
commit_hash_length = 4

[env_var.SHELL]
variable = "SHELL"
default = "unknown shell"
disabled = true

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'

# Show python version starting with venv
[python]
python_binary = ["./venv/bin/python", "python3", "python", "python2"]

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "
detect_extensions=["lua", "luau"]
lua_binary = "/home/compey/bin/lunev" 
# format = 'via [$symbol$version]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[rust]
symbol = " "
version_format = ""

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[os]
format = '[$symbol](bold white)'
disabled = false
